-- TASK-2 -- a started task no longer claims it was assigned.
--
-- ================================================================================================
-- WHAT CANON ACTUALLY SAYS, checked before changing anything.
--
-- `_ORVION_CANONICAL/26_state_machines.md`, Task State Machine:
--
--     | open    | in_progress | Responsible employee starts work        |
--     | overdue | in_progress | Work resumed on an overdue task         |
--
--     ## Required Events
--     - task_created
--     - task_assigned
--     - task_completed
--     - task_cancelled
--     - task_overdue
--
-- Two things follow, and neither is invented here.
--
-- FIRST, TASK-1's fix is confirmed by canon rather than by my judgement. Canon says the
-- **responsible employee** starts work. `202607055600` changed both `-> in_progress` transitions
-- from ASSIGN_TASK (managers only) to COMPLETE_TASK, which is what lets that employee do exactly
-- what canon describes. Recorded here because the previous migration argued it from the role model
-- and this is the authority.
--
-- SECOND, canon lists FIVE task events and none of them is a "started" event. So there is no
-- correct code to emit when a task enters `in_progress` -- and `advance_task` was emitting
-- `task_assigned`, which is not merely imprecise but false: nothing is assigned when the person
-- already holding a task begins working on it.
--
-- IT IS ALSO A DUPLICATE PRODUCER. `app.assign_task` already emits `task_assigned`, and that is the
-- correct producer -- assignment is what it does. So the audit stream contained `task_assigned` rows
-- generated by two different business actions, only one of which was an assignment. Anyone counting
-- assignments per employee, or reconstructing who was given what work, was reading inflated data.
--
-- ================================================================================================
-- WHY NO `task_started` EVENT IS ADDED
--
-- The obvious repair is a new event code. It is not taken, for the reason the owner directive gives
-- directly: "Do not add events merely because the catalog contains them. Do not fabricate lifecycle
-- states." Canon owns the state machines and deliberately enumerates five task events. Inventing a
-- sixth to make one transition read correctly would be ORVION's engineering inventing business
-- vocabulary, which is exactly the line this programme does not cross.
--
-- So the transition emits NOTHING. That is a real loss -- the moment work starts is no longer in the
-- event stream -- and it is the smaller loss: `tasks.task_status_code` and `tasks.updated_at` still
-- record the change, and a missing record is recoverable while a false one silently corrupts every
-- consumer that trusts it. If the business later wants start-of-work in the spine, that is a canon
-- amendment adding `task_started`, and it is recorded as such in MASTER_GAP_REGISTER.md.
--
-- The only structural change needed is that "this transition is valid" and "this transition has an
-- event" stop being the same test. `v_event is null` previously meant "no such transition"; it now
-- means "no event for this transition", and validity is carried by FOUND.
-- ================================================================================================

create or replace function app.advance_task(p_task_id uuid, p_to_status text, p_reason text default null)
returns void
language plpgsql
set search_path = ''
as $fn$
declare
    v_tenant uuid := app.current_tenant_id();
    v_actor uuid;
    v_status text;
    v_event text;
    v_perm text;
begin
    if v_tenant is null then
        raise exception 'no active tenant for caller';
    end if;

    select task_status_code into v_status
    from public.tasks where id = p_task_id and tenant_id = v_tenant;
    if v_status is null then
        raise exception 'task not found in your tenant';
    end if;

    select t.ev, t.perm into v_event, v_perm
    from (values
        -- Canon 26: "Responsible employee starts work". COMPLETE_TASK is the permission that role
        -- holds (TASK-1). The event is NULL because canon defines no start event and
        -- `app.assign_task` already owns `task_assigned` (TASK-2).
        ('open',        'in_progress', null::text,       'COMPLETE_TASK'),
        ('open',        'completed',   'task_completed', 'COMPLETE_TASK'),
        ('open',        'cancelled',   'task_cancelled', 'COMPLETE_TASK'),
        ('in_progress', 'completed',   'task_completed', 'COMPLETE_TASK'),
        ('in_progress', 'cancelled',   'task_cancelled', 'COMPLETE_TASK'),
        -- Canon 26: "Work resumed on an overdue task" -- resuming is not assignment either.
        ('overdue',     'in_progress', null::text,       'COMPLETE_TASK'),
        ('overdue',     'completed',   'task_completed', 'COMPLETE_TASK'),
        ('overdue',     'cancelled',   'task_cancelled', 'COMPLETE_TASK')
    ) as t(frm, to_s, ev, perm)
    where t.frm = v_status and t.to_s = p_to_status;

    -- VALIDITY IS NOW `FOUND`, NOT `v_event IS NULL`. Those were the same test while every
    -- transition had an event; they are different questions and conflating them would have made the
    -- two legitimate no-event transitions look like invalid ones.
    if not found then
        raise exception 'invalid task transition % -> %', v_status, p_to_status;
    end if;
    perform app.authorize(v_perm);

    select id into v_actor from public.users
    where auth_user_id = (select auth.uid()) and tenant_id = v_tenant;

    update public.tasks
    set task_status_code = p_to_status,
        completed_at = case when p_to_status = 'completed' then now() else completed_at end,
        updated_at = now()
    where id = p_task_id and tenant_id = v_tenant;

    if v_event is not null then
        perform app.record_event(
            v_tenant, v_event, 'task', p_task_id, v_actor, v_status, p_to_status, p_reason, null, 'info');
    end if;
end;
$fn$;

revoke execute on function app.advance_task(uuid, text, text) from public;
grant  execute on function app.advance_task(uuid, text, text) to authenticated;
