-- Migration: tenant_qualified_foreign_keys
-- Plan reference: SPEC-129. Resolves TENANT-1 — every tenant-scoped foreign key in ORVION could
-- reference a row belonging to a DIFFERENT tenant.
--
-- THE DEFECT (reproduced on the local database, 2026-08-21, before any fix):
--     insert into bookings (tenant_id, customer_id, ...) values (TENANT_B, TENANT_A_CUSTOMER, ...);
--     -- ACCEPTED
--     select b.tenant_id, c.tenant_id from bookings b join customers c on c.id = b.customer_id;
--       booking_tenant                       | customer_tenant
--       bbbb0000-...-00000000000b            | aaaa0000-...-00000000000a
--     insert into leads (tenant_id, customer_id, ...) values (TENANT_B, TENANT_A_CUSTOMER, ...);
--     -- ACCEPTED
--
-- A single-column foreign key answers "does this row exist?" It does not answer "does this row
-- belong to me?" RLS closes the READ side — a tenant cannot see another tenant's rows — but RLS's
-- WITH CHECK only validates the NEW row's own tenant_id, so nothing stopped a tenant from writing a
-- reference that points across the boundary. The result is not a data leak so much as silent data
-- corruption: the child row is visible to its owner while its parent is not, so joins drop rows and
-- SECURITY DEFINER paths (reporting, integrations) can traverse a link that should not exist.
--
-- SCALE, measured rather than estimated: 189 single-column foreign keys, across 50 child tables,
-- pointing at 26 tenant-scoped parents. Zero composite tenant keys existed. Every one of the 189
-- was exposed. This is not a property of any one table; it is a property of the whole schema.
--
-- THE FIX is the standard multi-tenant remedy and is mechanical: give every tenant-scoped parent a
-- UNIQUE (tenant_id, id) natural key, then re-point each child FK at that composite key, carrying
-- the child's own tenant_id into the reference. A cross-tenant write then fails at the database,
-- not at whichever application layer happened to remember to check.
--
-- The child's tenant_id is NOT NULL on all 50 tables while the referencing column is often
-- nullable, and MATCH SIMPLE (the default) skips enforcement when any referencing column is NULL.
-- That is exactly the semantics wanted: an absent optional relationship stays absent and
-- unchecked, a present one must be same-tenant.
--
-- Referential actions are carried across unchanged, preserving ADR-0007 (restrict by default);
-- the smoke-test's CHECK 7 re-verifies that after this migration.
--
-- WHY NOW. At zero rows this is a pure DDL change. After go-live it requires validating every
-- existing row and repairing whatever cross-tenant references had already been written — and those
-- are unrepairable without knowing which tenant the row was meant for. The generated statements
-- below were produced by introspecting the live FK graph, not written by hand, so no relationship
-- is missed and none is transcribed wrongly.

alter table public.attribution_clicks add constraint attribution_clicks_tenant_id_id_key unique (tenant_id, id);
alter table public.booking_items add constraint booking_items_tenant_id_id_key unique (tenant_id, id);
alter table public.bookings add constraint bookings_tenant_id_id_key unique (tenant_id, id);
alter table public.branches add constraint branches_tenant_id_id_key unique (tenant_id, id);
alter table public.chart_of_accounts add constraint chart_of_accounts_tenant_id_id_key unique (tenant_id, id);
alter table public.conversations add constraint conversations_tenant_id_id_key unique (tenant_id, id);
alter table public.customers add constraint customers_tenant_id_id_key unique (tenant_id, id);
alter table public.departments add constraint departments_tenant_id_id_key unique (tenant_id, id);
alter table public.document_versions add constraint document_versions_tenant_id_id_key unique (tenant_id, id);
alter table public.documents add constraint documents_tenant_id_id_key unique (tenant_id, id);
alter table public.exchange_rates add constraint exchange_rates_tenant_id_id_key unique (tenant_id, id);
alter table public.financial_accounts add constraint financial_accounts_tenant_id_id_key unique (tenant_id, id);
alter table public.invoices add constraint invoices_tenant_id_id_key unique (tenant_id, id);
alter table public.journal_entries add constraint journal_entries_tenant_id_id_key unique (tenant_id, id);
alter table public.leads add constraint leads_tenant_id_id_key unique (tenant_id, id);
alter table public.marketing_campaigns add constraint marketing_campaigns_tenant_id_id_key unique (tenant_id, id);
alter table public.notifications add constraint notifications_tenant_id_id_key unique (tenant_id, id);
alter table public.offline_conversions add constraint offline_conversions_tenant_id_id_key unique (tenant_id, id);
alter table public.passengers add constraint passengers_tenant_id_id_key unique (tenant_id, id);
alter table public.payments add constraint payments_tenant_id_id_key unique (tenant_id, id);
alter table public.quotations add constraint quotations_tenant_id_id_key unique (tenant_id, id);
alter table public.receipts add constraint receipts_tenant_id_id_key unique (tenant_id, id);
alter table public.subscription_payment_proofs add constraint subscription_payment_proofs_tenant_id_id_key unique (tenant_id, id);
alter table public.subscriptions add constraint subscriptions_tenant_id_id_key unique (tenant_id, id);
alter table public.suppliers add constraint suppliers_tenant_id_id_key unique (tenant_id, id);
alter table public.users add constraint users_tenant_id_id_key unique (tenant_id, id);
alter table public.approval_requests drop constraint approval_requests_booking_item_id_fkey, add constraint approval_requests_booking_item_id_fkey foreign key (tenant_id, booking_item_id) references public.booking_items (tenant_id, id) on delete restrict on update no action;
alter table public.approval_requests drop constraint approval_requests_document_id_fkey, add constraint approval_requests_document_id_fkey foreign key (tenant_id, document_id) references public.documents (tenant_id, id) on delete restrict on update no action;
alter table public.approval_requests drop constraint approval_requests_requested_by_fkey, add constraint approval_requests_requested_by_fkey foreign key (tenant_id, requested_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.approval_requests drop constraint approval_requests_reviewed_by_fkey, add constraint approval_requests_reviewed_by_fkey foreign key (tenant_id, reviewed_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.attribution_clicks drop constraint attribution_clicks_lead_id_fkey, add constraint attribution_clicks_lead_id_fkey foreign key (tenant_id, lead_id) references public.leads (tenant_id, id) on delete restrict on update no action;
alter table public.attribution_clicks drop constraint attribution_clicks_marketing_campaign_id_fkey, add constraint attribution_clicks_marketing_campaign_id_fkey foreign key (tenant_id, marketing_campaign_id) references public.marketing_campaigns (tenant_id, id) on delete restrict on update no action;
alter table public.booking_item_passengers drop constraint booking_item_passengers_booking_item_id_fkey, add constraint booking_item_passengers_booking_item_id_fkey foreign key (tenant_id, booking_item_id) references public.booking_items (tenant_id, id) on delete restrict on update no action;
alter table public.booking_item_passengers drop constraint booking_item_passengers_passenger_id_fkey, add constraint booking_item_passengers_passenger_id_fkey foreign key (tenant_id, passenger_id) references public.passengers (tenant_id, id) on delete restrict on update no action;
alter table public.booking_items drop constraint booking_items_archived_by_fkey, add constraint booking_items_archived_by_fkey foreign key (tenant_id, archived_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.booking_items drop constraint booking_items_booking_id_fkey, add constraint booking_items_booking_id_fkey foreign key (tenant_id, booking_id) references public.bookings (tenant_id, id) on delete restrict on update no action;
alter table public.booking_items drop constraint booking_items_cancelled_by_fkey, add constraint booking_items_cancelled_by_fkey foreign key (tenant_id, cancelled_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.booking_items drop constraint booking_items_created_by_fkey, add constraint booking_items_created_by_fkey foreign key (tenant_id, created_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.booking_items drop constraint booking_items_exchange_rate_id_fkey, add constraint booking_items_exchange_rate_id_fkey foreign key (tenant_id, exchange_rate_id) references public.exchange_rates (tenant_id, id) on delete restrict on update no action;
alter table public.booking_items drop constraint booking_items_no_show_recorded_by_fkey, add constraint booking_items_no_show_recorded_by_fkey foreign key (tenant_id, no_show_recorded_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.booking_items drop constraint booking_items_operational_owner_user_id_fkey, add constraint booking_items_operational_owner_user_id_fkey foreign key (tenant_id, operational_owner_user_id) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.booking_items drop constraint booking_items_owner_branch_id_fkey, add constraint booking_items_owner_branch_id_fkey foreign key (tenant_id, owner_branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.booking_items drop constraint booking_items_owner_department_id_fkey, add constraint booking_items_owner_department_id_fkey foreign key (tenant_id, owner_department_id) references public.departments (tenant_id, id) on delete restrict on update no action;
alter table public.booking_items drop constraint booking_items_owner_user_id_fkey, add constraint booking_items_owner_user_id_fkey foreign key (tenant_id, owner_user_id) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.booking_items drop constraint booking_items_sales_owner_branch_id_fkey, add constraint booking_items_sales_owner_branch_id_fkey foreign key (tenant_id, sales_owner_branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.booking_items drop constraint booking_items_sales_owner_department_id_fkey, add constraint booking_items_sales_owner_department_id_fkey foreign key (tenant_id, sales_owner_department_id) references public.departments (tenant_id, id) on delete restrict on update no action;
alter table public.booking_items drop constraint booking_items_sales_owner_user_id_fkey, add constraint booking_items_sales_owner_user_id_fkey foreign key (tenant_id, sales_owner_user_id) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.booking_items drop constraint booking_items_supplier_id_fkey, add constraint booking_items_supplier_id_fkey foreign key (tenant_id, supplier_id) references public.suppliers (tenant_id, id) on delete restrict on update no action;
alter table public.bookings drop constraint bookings_archived_by_fkey, add constraint bookings_archived_by_fkey foreign key (tenant_id, archived_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.bookings drop constraint bookings_branch_id_fkey, add constraint bookings_branch_id_fkey foreign key (tenant_id, branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.bookings drop constraint bookings_created_by_fkey, add constraint bookings_created_by_fkey foreign key (tenant_id, created_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.bookings drop constraint bookings_customer_id_fkey, add constraint bookings_customer_id_fkey foreign key (tenant_id, customer_id) references public.customers (tenant_id, id) on delete restrict on update no action;
alter table public.bookings drop constraint bookings_department_id_fkey, add constraint bookings_department_id_fkey foreign key (tenant_id, department_id) references public.departments (tenant_id, id) on delete restrict on update no action;
alter table public.bookings drop constraint bookings_lead_id_fkey, add constraint bookings_lead_id_fkey foreign key (tenant_id, lead_id) references public.leads (tenant_id, id) on delete restrict on update no action;
alter table public.bookings drop constraint bookings_owner_branch_id_fkey, add constraint bookings_owner_branch_id_fkey foreign key (tenant_id, owner_branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.bookings drop constraint bookings_owner_department_id_fkey, add constraint bookings_owner_department_id_fkey foreign key (tenant_id, owner_department_id) references public.departments (tenant_id, id) on delete restrict on update no action;
alter table public.bookings drop constraint bookings_owner_user_id_fkey, add constraint bookings_owner_user_id_fkey foreign key (tenant_id, owner_user_id) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.bookings drop constraint bookings_quotation_id_fkey, add constraint bookings_quotation_id_fkey foreign key (tenant_id, quotation_id) references public.quotations (tenant_id, id) on delete restrict on update no action;
alter table public.branch_business_hours drop constraint branch_business_hours_branch_id_fkey, add constraint branch_business_hours_branch_id_fkey foreign key (tenant_id, branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.campaign_daily_metrics drop constraint campaign_daily_metrics_marketing_campaign_id_fkey, add constraint campaign_daily_metrics_marketing_campaign_id_fkey foreign key (tenant_id, marketing_campaign_id) references public.marketing_campaigns (tenant_id, id) on delete restrict on update no action;
alter table public.catalog_values drop constraint catalog_values_created_by_fkey, add constraint catalog_values_created_by_fkey foreign key (tenant_id, created_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.chart_of_accounts drop constraint chart_of_accounts_parent_account_id_fkey, add constraint chart_of_accounts_parent_account_id_fkey foreign key (tenant_id, parent_account_id) references public.chart_of_accounts (tenant_id, id) on delete restrict on update no action;
alter table public.complaints drop constraint complaints_archived_by_fkey, add constraint complaints_archived_by_fkey foreign key (tenant_id, archived_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.complaints drop constraint complaints_booking_id_fkey, add constraint complaints_booking_id_fkey foreign key (tenant_id, booking_id) references public.bookings (tenant_id, id) on delete restrict on update no action;
alter table public.complaints drop constraint complaints_booking_item_id_fkey, add constraint complaints_booking_item_id_fkey foreign key (tenant_id, booking_item_id) references public.booking_items (tenant_id, id) on delete restrict on update no action;
alter table public.complaints drop constraint complaints_created_by_fkey, add constraint complaints_created_by_fkey foreign key (tenant_id, created_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.complaints drop constraint complaints_customer_id_fkey, add constraint complaints_customer_id_fkey foreign key (tenant_id, customer_id) references public.customers (tenant_id, id) on delete restrict on update no action;
alter table public.complaints drop constraint complaints_owner_branch_id_fkey, add constraint complaints_owner_branch_id_fkey foreign key (tenant_id, owner_branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.complaints drop constraint complaints_owner_department_id_fkey, add constraint complaints_owner_department_id_fkey foreign key (tenant_id, owner_department_id) references public.departments (tenant_id, id) on delete restrict on update no action;
alter table public.complaints drop constraint complaints_owner_user_id_fkey, add constraint complaints_owner_user_id_fkey foreign key (tenant_id, owner_user_id) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.conversation_messages drop constraint conversation_messages_conversation_id_fkey, add constraint conversation_messages_conversation_id_fkey foreign key (tenant_id, conversation_id) references public.conversations (tenant_id, id) on delete restrict on update no action;
alter table public.conversation_messages drop constraint conversation_messages_sender_user_id_fkey, add constraint conversation_messages_sender_user_id_fkey foreign key (tenant_id, sender_user_id) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.conversations drop constraint conversations_booking_id_fkey, add constraint conversations_booking_id_fkey foreign key (tenant_id, booking_id) references public.bookings (tenant_id, id) on delete restrict on update no action;
alter table public.conversations drop constraint conversations_booking_item_id_fkey, add constraint conversations_booking_item_id_fkey foreign key (tenant_id, booking_item_id) references public.booking_items (tenant_id, id) on delete restrict on update no action;
alter table public.conversations drop constraint conversations_current_branch_id_fkey, add constraint conversations_current_branch_id_fkey foreign key (tenant_id, current_branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.conversations drop constraint conversations_current_department_id_fkey, add constraint conversations_current_department_id_fkey foreign key (tenant_id, current_department_id) references public.departments (tenant_id, id) on delete restrict on update no action;
alter table public.conversations drop constraint conversations_customer_id_fkey, add constraint conversations_customer_id_fkey foreign key (tenant_id, customer_id) references public.customers (tenant_id, id) on delete restrict on update no action;
alter table public.conversations drop constraint conversations_lead_id_fkey, add constraint conversations_lead_id_fkey foreign key (tenant_id, lead_id) references public.leads (tenant_id, id) on delete restrict on update no action;
alter table public.conversations drop constraint conversations_owner_branch_id_fkey, add constraint conversations_owner_branch_id_fkey foreign key (tenant_id, owner_branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.conversations drop constraint conversations_owner_department_id_fkey, add constraint conversations_owner_department_id_fkey foreign key (tenant_id, owner_department_id) references public.departments (tenant_id, id) on delete restrict on update no action;
alter table public.conversations drop constraint conversations_owner_user_id_fkey, add constraint conversations_owner_user_id_fkey foreign key (tenant_id, owner_user_id) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.customer_contact_methods drop constraint customer_contact_methods_customer_id_fkey, add constraint customer_contact_methods_customer_id_fkey foreign key (tenant_id, customer_id) references public.customers (tenant_id, id) on delete restrict on update no action;
alter table public.customer_identity_merges drop constraint customer_identity_merges_merged_by_fkey, add constraint customer_identity_merges_merged_by_fkey foreign key (tenant_id, merged_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.customer_identity_merges drop constraint customer_identity_merges_source_customer_id_fkey, add constraint customer_identity_merges_source_customer_id_fkey foreign key (tenant_id, source_customer_id) references public.customers (tenant_id, id) on delete restrict on update no action;
alter table public.customer_identity_merges drop constraint customer_identity_merges_target_customer_id_fkey, add constraint customer_identity_merges_target_customer_id_fkey foreign key (tenant_id, target_customer_id) references public.customers (tenant_id, id) on delete restrict on update no action;
alter table public.customer_identity_signals drop constraint customer_identity_signals_customer_id_fkey, add constraint customer_identity_signals_customer_id_fkey foreign key (tenant_id, customer_id) references public.customers (tenant_id, id) on delete restrict on update no action;
alter table public.customer_notes drop constraint customer_notes_archived_by_fkey, add constraint customer_notes_archived_by_fkey foreign key (tenant_id, archived_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.customer_notes drop constraint customer_notes_created_by_fkey, add constraint customer_notes_created_by_fkey foreign key (tenant_id, created_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.customer_notes drop constraint customer_notes_customer_id_fkey, add constraint customer_notes_customer_id_fkey foreign key (tenant_id, customer_id) references public.customers (tenant_id, id) on delete restrict on update no action;
alter table public.customers drop constraint customers_archived_by_fkey, add constraint customers_archived_by_fkey foreign key (tenant_id, archived_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.customers drop constraint customers_created_by_fkey, add constraint customers_created_by_fkey foreign key (tenant_id, created_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.customers drop constraint customers_first_registered_branch_id_fkey, add constraint customers_first_registered_branch_id_fkey foreign key (tenant_id, first_registered_branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.customers drop constraint customers_last_interaction_branch_id_fkey, add constraint customers_last_interaction_branch_id_fkey foreign key (tenant_id, last_interaction_branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.customers drop constraint customers_last_interaction_user_id_fkey, add constraint customers_last_interaction_user_id_fkey foreign key (tenant_id, last_interaction_user_id) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.departments drop constraint departments_branch_id_fkey, add constraint departments_branch_id_fkey foreign key (tenant_id, branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.document_links drop constraint document_links_booking_id_fkey, add constraint document_links_booking_id_fkey foreign key (tenant_id, booking_id) references public.bookings (tenant_id, id) on delete restrict on update no action;
alter table public.document_links drop constraint document_links_booking_item_id_fkey, add constraint document_links_booking_item_id_fkey foreign key (tenant_id, booking_item_id) references public.booking_items (tenant_id, id) on delete restrict on update no action;
alter table public.document_links drop constraint document_links_created_by_fkey, add constraint document_links_created_by_fkey foreign key (tenant_id, created_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.document_links drop constraint document_links_document_id_fkey, add constraint document_links_document_id_fkey foreign key (tenant_id, document_id) references public.documents (tenant_id, id) on delete restrict on update no action;
alter table public.document_links drop constraint document_links_invoice_id_fkey, add constraint document_links_invoice_id_fkey foreign key (tenant_id, invoice_id) references public.invoices (tenant_id, id) on delete restrict on update no action;
alter table public.document_links drop constraint document_links_passenger_id_fkey, add constraint document_links_passenger_id_fkey foreign key (tenant_id, passenger_id) references public.passengers (tenant_id, id) on delete restrict on update no action;
alter table public.document_links drop constraint document_links_quotation_id_fkey, add constraint document_links_quotation_id_fkey foreign key (tenant_id, quotation_id) references public.quotations (tenant_id, id) on delete restrict on update no action;
alter table public.document_links drop constraint document_links_receipt_id_fkey, add constraint document_links_receipt_id_fkey foreign key (tenant_id, receipt_id) references public.receipts (tenant_id, id) on delete restrict on update no action;
alter table public.document_links drop constraint document_links_subscription_payment_proof_id_fkey, add constraint document_links_subscription_payment_proof_id_fkey foreign key (tenant_id, subscription_payment_proof_id) references public.subscription_payment_proofs (tenant_id, id) on delete restrict on update no action;
alter table public.document_links drop constraint document_links_supplier_id_fkey, add constraint document_links_supplier_id_fkey foreign key (tenant_id, supplier_id) references public.suppliers (tenant_id, id) on delete restrict on update no action;
alter table public.document_versions drop constraint document_versions_document_id_fkey, add constraint document_versions_document_id_fkey foreign key (tenant_id, document_id) references public.documents (tenant_id, id) on delete restrict on update no action;
alter table public.document_versions drop constraint document_versions_uploaded_by_fkey, add constraint document_versions_uploaded_by_fkey foreign key (tenant_id, uploaded_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.documents drop constraint documents_archived_by_fkey, add constraint documents_archived_by_fkey foreign key (tenant_id, archived_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.documents drop constraint documents_created_by_fkey, add constraint documents_created_by_fkey foreign key (tenant_id, created_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.documents drop constraint documents_current_version_id_fkey, add constraint documents_current_version_id_fkey foreign key (tenant_id, current_version_id) references public.document_versions (tenant_id, id) on delete restrict on update no action;
alter table public.events drop constraint events_actor_user_id_fkey, add constraint events_actor_user_id_fkey foreign key (tenant_id, actor_user_id) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.exchange_rate_adjustments drop constraint exchange_rate_adjustments_booking_item_id_fkey, add constraint exchange_rate_adjustments_booking_item_id_fkey foreign key (tenant_id, booking_item_id) references public.booking_items (tenant_id, id) on delete restrict on update no action;
alter table public.exchange_rate_adjustments drop constraint exchange_rate_adjustments_created_by_fkey, add constraint exchange_rate_adjustments_created_by_fkey foreign key (tenant_id, created_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.exchange_rate_adjustments drop constraint exchange_rate_adjustments_new_exchange_rate_id_fkey, add constraint exchange_rate_adjustments_new_exchange_rate_id_fkey foreign key (tenant_id, new_exchange_rate_id) references public.exchange_rates (tenant_id, id) on delete restrict on update no action;
alter table public.exchange_rate_adjustments drop constraint exchange_rate_adjustments_original_exchange_rate_id_fkey, add constraint exchange_rate_adjustments_original_exchange_rate_id_fkey foreign key (tenant_id, original_exchange_rate_id) references public.exchange_rates (tenant_id, id) on delete restrict on update no action;
alter table public.exchange_rates drop constraint exchange_rates_set_by_fkey, add constraint exchange_rates_set_by_fkey foreign key (tenant_id, set_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.holidays drop constraint holidays_branch_id_fkey, add constraint holidays_branch_id_fkey foreign key (tenant_id, branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.internal_supplier_links drop constraint internal_supplier_links_booking_item_id_fkey, add constraint internal_supplier_links_booking_item_id_fkey foreign key (tenant_id, booking_item_id) references public.booking_items (tenant_id, id) on delete restrict on update no action;
alter table public.internal_supplier_links drop constraint internal_supplier_links_provider_branch_id_fkey, add constraint internal_supplier_links_provider_branch_id_fkey foreign key (tenant_id, provider_branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.internal_supplier_links drop constraint internal_supplier_links_provider_department_id_fkey, add constraint internal_supplier_links_provider_department_id_fkey foreign key (tenant_id, provider_department_id) references public.departments (tenant_id, id) on delete restrict on update no action;
alter table public.internal_supplier_links drop constraint internal_supplier_links_requester_branch_id_fkey, add constraint internal_supplier_links_requester_branch_id_fkey foreign key (tenant_id, requester_branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.internal_supplier_links drop constraint internal_supplier_links_requester_department_id_fkey, add constraint internal_supplier_links_requester_department_id_fkey foreign key (tenant_id, requester_department_id) references public.departments (tenant_id, id) on delete restrict on update no action;
alter table public.invoices drop constraint invoices_archived_by_fkey, add constraint invoices_archived_by_fkey foreign key (tenant_id, archived_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.invoices drop constraint invoices_booking_id_fkey, add constraint invoices_booking_id_fkey foreign key (tenant_id, booking_id) references public.bookings (tenant_id, id) on delete restrict on update no action;
alter table public.invoices drop constraint invoices_booking_item_id_fkey, add constraint invoices_booking_item_id_fkey foreign key (tenant_id, booking_item_id) references public.booking_items (tenant_id, id) on delete restrict on update no action;
alter table public.invoices drop constraint invoices_created_by_fkey, add constraint invoices_created_by_fkey foreign key (tenant_id, created_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.invoices drop constraint invoices_customer_id_fkey, add constraint invoices_customer_id_fkey foreign key (tenant_id, customer_id) references public.customers (tenant_id, id) on delete restrict on update no action;
alter table public.invoices drop constraint invoices_voided_by_fkey, add constraint invoices_voided_by_fkey foreign key (tenant_id, voided_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.journal_entries drop constraint journal_entries_created_by_fkey, add constraint journal_entries_created_by_fkey foreign key (tenant_id, created_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.journal_entries drop constraint journal_entries_voided_by_fkey, add constraint journal_entries_voided_by_fkey foreign key (tenant_id, voided_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.journal_entry_lines drop constraint journal_entry_lines_chart_account_id_fkey, add constraint journal_entry_lines_chart_account_id_fkey foreign key (tenant_id, chart_account_id) references public.chart_of_accounts (tenant_id, id) on delete restrict on update no action;
alter table public.journal_entry_lines drop constraint journal_entry_lines_journal_entry_id_fkey, add constraint journal_entry_lines_journal_entry_id_fkey foreign key (tenant_id, journal_entry_id) references public.journal_entries (tenant_id, id) on delete restrict on update no action;
alter table public.lead_assignments drop constraint lead_assignments_assigned_by_fkey, add constraint lead_assignments_assigned_by_fkey foreign key (tenant_id, assigned_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.lead_assignments drop constraint lead_assignments_assigned_user_id_fkey, add constraint lead_assignments_assigned_user_id_fkey foreign key (tenant_id, assigned_user_id) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.lead_assignments drop constraint lead_assignments_lead_id_fkey, add constraint lead_assignments_lead_id_fkey foreign key (tenant_id, lead_id) references public.leads (tenant_id, id) on delete restrict on update no action;
alter table public.lead_interactions drop constraint lead_interactions_lead_id_fkey, add constraint lead_interactions_lead_id_fkey foreign key (tenant_id, lead_id) references public.leads (tenant_id, id) on delete restrict on update no action;
alter table public.lead_interactions drop constraint lead_interactions_user_id_fkey, add constraint lead_interactions_user_id_fkey foreign key (tenant_id, user_id) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.leads drop constraint leads_archived_by_fkey, add constraint leads_archived_by_fkey foreign key (tenant_id, archived_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.leads drop constraint leads_assigned_user_id_fkey, add constraint leads_assigned_user_id_fkey foreign key (tenant_id, assigned_user_id) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.leads drop constraint leads_attribution_click_id_fkey, add constraint leads_attribution_click_id_fkey foreign key (tenant_id, attribution_click_id) references public.attribution_clicks (tenant_id, id) on delete restrict on update no action;
alter table public.leads drop constraint leads_branch_id_fkey, add constraint leads_branch_id_fkey foreign key (tenant_id, branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.leads drop constraint leads_created_by_fkey, add constraint leads_created_by_fkey foreign key (tenant_id, created_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.leads drop constraint leads_customer_id_fkey, add constraint leads_customer_id_fkey foreign key (tenant_id, customer_id) references public.customers (tenant_id, id) on delete restrict on update no action;
alter table public.leads drop constraint leads_department_id_fkey, add constraint leads_department_id_fkey foreign key (tenant_id, department_id) references public.departments (tenant_id, id) on delete restrict on update no action;
alter table public.leads drop constraint leads_owner_branch_id_fkey, add constraint leads_owner_branch_id_fkey foreign key (tenant_id, owner_branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.leads drop constraint leads_owner_department_id_fkey, add constraint leads_owner_department_id_fkey foreign key (tenant_id, owner_department_id) references public.departments (tenant_id, id) on delete restrict on update no action;
alter table public.leads drop constraint leads_owner_user_id_fkey, add constraint leads_owner_user_id_fkey foreign key (tenant_id, owner_user_id) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.notification_deliveries drop constraint notification_deliveries_notification_id_fkey, add constraint notification_deliveries_notification_id_fkey foreign key (tenant_id, notification_id) references public.notifications (tenant_id, id) on delete restrict on update no action;
alter table public.notifications drop constraint notifications_target_user_id_fkey, add constraint notifications_target_user_id_fkey foreign key (tenant_id, target_user_id) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.offline_conversion_deliveries drop constraint offline_conversion_deliveries_offline_conversion_id_fkey, add constraint offline_conversion_deliveries_offline_conversion_id_fkey foreign key (tenant_id, offline_conversion_id) references public.offline_conversions (tenant_id, id) on delete restrict on update no action;
alter table public.offline_conversions drop constraint offline_conversions_attribution_click_id_fkey, add constraint offline_conversions_attribution_click_id_fkey foreign key (tenant_id, attribution_click_id) references public.attribution_clicks (tenant_id, id) on delete restrict on update no action;
alter table public.offline_conversions drop constraint offline_conversions_booking_id_fkey, add constraint offline_conversions_booking_id_fkey foreign key (tenant_id, booking_id) references public.bookings (tenant_id, id) on delete restrict on update no action;
alter table public.offline_conversions drop constraint offline_conversions_booking_item_id_fkey, add constraint offline_conversions_booking_item_id_fkey foreign key (tenant_id, booking_item_id) references public.booking_items (tenant_id, id) on delete restrict on update no action;
alter table public.offline_conversions drop constraint offline_conversions_customer_id_fkey, add constraint offline_conversions_customer_id_fkey foreign key (tenant_id, customer_id) references public.customers (tenant_id, id) on delete restrict on update no action;
alter table public.offline_conversions drop constraint offline_conversions_lead_id_fkey, add constraint offline_conversions_lead_id_fkey foreign key (tenant_id, lead_id) references public.leads (tenant_id, id) on delete restrict on update no action;
alter table public.offline_conversions drop constraint offline_conversions_marketing_campaign_id_fkey, add constraint offline_conversions_marketing_campaign_id_fkey foreign key (tenant_id, marketing_campaign_id) references public.marketing_campaigns (tenant_id, id) on delete restrict on update no action;
alter table public.offline_conversions drop constraint offline_conversions_payment_id_fkey, add constraint offline_conversions_payment_id_fkey foreign key (tenant_id, payment_id) references public.payments (tenant_id, id) on delete restrict on update no action;
alter table public.passengers drop constraint passengers_archived_by_fkey, add constraint passengers_archived_by_fkey foreign key (tenant_id, archived_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.passengers drop constraint passengers_customer_id_fkey, add constraint passengers_customer_id_fkey foreign key (tenant_id, customer_id) references public.customers (tenant_id, id) on delete restrict on update no action;
alter table public.payment_allocations drop constraint payment_allocations_created_by_fkey, add constraint payment_allocations_created_by_fkey foreign key (tenant_id, created_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.payment_allocations drop constraint payment_allocations_exchange_rate_id_fkey, add constraint payment_allocations_exchange_rate_id_fkey foreign key (tenant_id, exchange_rate_id) references public.exchange_rates (tenant_id, id) on delete restrict on update no action;
alter table public.payment_allocations drop constraint payment_allocations_invoice_id_fkey, add constraint payment_allocations_invoice_id_fkey foreign key (tenant_id, invoice_id) references public.invoices (tenant_id, id) on delete restrict on update no action;
alter table public.payment_allocations drop constraint payment_allocations_payment_id_fkey, add constraint payment_allocations_payment_id_fkey foreign key (tenant_id, payment_id) references public.payments (tenant_id, id) on delete restrict on update no action;
alter table public.payments drop constraint payments_booking_id_fkey, add constraint payments_booking_id_fkey foreign key (tenant_id, booking_id) references public.bookings (tenant_id, id) on delete restrict on update no action;
alter table public.payments drop constraint payments_booking_item_id_fkey, add constraint payments_booking_item_id_fkey foreign key (tenant_id, booking_item_id) references public.booking_items (tenant_id, id) on delete restrict on update no action;
alter table public.payments drop constraint payments_created_by_fkey, add constraint payments_created_by_fkey foreign key (tenant_id, created_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.payments drop constraint payments_customer_id_fkey, add constraint payments_customer_id_fkey foreign key (tenant_id, customer_id) references public.customers (tenant_id, id) on delete restrict on update no action;
alter table public.payments drop constraint payments_financial_account_id_fkey, add constraint payments_financial_account_id_fkey foreign key (tenant_id, financial_account_id) references public.financial_accounts (tenant_id, id) on delete restrict on update no action;
alter table public.payments drop constraint payments_received_by_fkey, add constraint payments_received_by_fkey foreign key (tenant_id, received_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.payments drop constraint payments_supplier_id_fkey, add constraint payments_supplier_id_fkey foreign key (tenant_id, supplier_id) references public.suppliers (tenant_id, id) on delete restrict on update no action;
alter table public.payments drop constraint payments_verified_by_fkey, add constraint payments_verified_by_fkey foreign key (tenant_id, verified_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.quotation_items drop constraint quotation_items_quotation_id_fkey, add constraint quotation_items_quotation_id_fkey foreign key (tenant_id, quotation_id) references public.quotations (tenant_id, id) on delete restrict on update no action;
alter table public.quotations drop constraint quotations_archived_by_fkey, add constraint quotations_archived_by_fkey foreign key (tenant_id, archived_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.quotations drop constraint quotations_created_by_fkey, add constraint quotations_created_by_fkey foreign key (tenant_id, created_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.quotations drop constraint quotations_customer_id_fkey, add constraint quotations_customer_id_fkey foreign key (tenant_id, customer_id) references public.customers (tenant_id, id) on delete restrict on update no action;
alter table public.quotations drop constraint quotations_lead_id_fkey, add constraint quotations_lead_id_fkey foreign key (tenant_id, lead_id) references public.leads (tenant_id, id) on delete restrict on update no action;
alter table public.quotations drop constraint quotations_owner_branch_id_fkey, add constraint quotations_owner_branch_id_fkey foreign key (tenant_id, owner_branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.quotations drop constraint quotations_owner_department_id_fkey, add constraint quotations_owner_department_id_fkey foreign key (tenant_id, owner_department_id) references public.departments (tenant_id, id) on delete restrict on update no action;
alter table public.quotations drop constraint quotations_owner_user_id_fkey, add constraint quotations_owner_user_id_fkey foreign key (tenant_id, owner_user_id) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.receipts drop constraint receipts_created_by_fkey, add constraint receipts_created_by_fkey foreign key (tenant_id, created_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.receipts drop constraint receipts_payment_id_fkey, add constraint receipts_payment_id_fkey foreign key (tenant_id, payment_id) references public.payments (tenant_id, id) on delete restrict on update no action;
alter table public.refunds drop constraint refunds_booking_id_fkey, add constraint refunds_booking_id_fkey foreign key (tenant_id, booking_id) references public.bookings (tenant_id, id) on delete restrict on update no action;
alter table public.refunds drop constraint refunds_booking_item_id_fkey, add constraint refunds_booking_item_id_fkey foreign key (tenant_id, booking_item_id) references public.booking_items (tenant_id, id) on delete restrict on update no action;
alter table public.refunds drop constraint refunds_created_by_fkey, add constraint refunds_created_by_fkey foreign key (tenant_id, created_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.refunds drop constraint refunds_customer_id_fkey, add constraint refunds_customer_id_fkey foreign key (tenant_id, customer_id) references public.customers (tenant_id, id) on delete restrict on update no action;
alter table public.refunds drop constraint refunds_original_payment_id_fkey, add constraint refunds_original_payment_id_fkey foreign key (tenant_id, original_payment_id) references public.payments (tenant_id, id) on delete restrict on update no action;
alter table public.refunds drop constraint refunds_supplier_id_fkey, add constraint refunds_supplier_id_fkey foreign key (tenant_id, supplier_id) references public.suppliers (tenant_id, id) on delete restrict on update no action;
alter table public.security_events drop constraint security_events_user_id_fkey, add constraint security_events_user_id_fkey foreign key (tenant_id, user_id) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.service_requests drop constraint service_requests_archived_by_fkey, add constraint service_requests_archived_by_fkey foreign key (tenant_id, archived_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.service_requests drop constraint service_requests_booking_id_fkey, add constraint service_requests_booking_id_fkey foreign key (tenant_id, booking_id) references public.bookings (tenant_id, id) on delete restrict on update no action;
alter table public.service_requests drop constraint service_requests_booking_item_id_fkey, add constraint service_requests_booking_item_id_fkey foreign key (tenant_id, booking_item_id) references public.booking_items (tenant_id, id) on delete restrict on update no action;
alter table public.service_requests drop constraint service_requests_created_by_fkey, add constraint service_requests_created_by_fkey foreign key (tenant_id, created_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.service_requests drop constraint service_requests_customer_id_fkey, add constraint service_requests_customer_id_fkey foreign key (tenant_id, customer_id) references public.customers (tenant_id, id) on delete restrict on update no action;
alter table public.service_requests drop constraint service_requests_owner_branch_id_fkey, add constraint service_requests_owner_branch_id_fkey foreign key (tenant_id, owner_branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.service_requests drop constraint service_requests_owner_department_id_fkey, add constraint service_requests_owner_department_id_fkey foreign key (tenant_id, owner_department_id) references public.departments (tenant_id, id) on delete restrict on update no action;
alter table public.service_requests drop constraint service_requests_owner_user_id_fkey, add constraint service_requests_owner_user_id_fkey foreign key (tenant_id, owner_user_id) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.subscription_payment_proofs drop constraint subscription_payment_proofs_document_id_fkey, add constraint subscription_payment_proofs_document_id_fkey foreign key (tenant_id, document_id) references public.documents (tenant_id, id) on delete restrict on update no action;
alter table public.subscription_payment_proofs drop constraint subscription_payment_proofs_reviewed_by_fkey, add constraint subscription_payment_proofs_reviewed_by_fkey foreign key (tenant_id, reviewed_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.subscription_payment_proofs drop constraint subscription_payment_proofs_subscription_id_fkey, add constraint subscription_payment_proofs_subscription_id_fkey foreign key (tenant_id, subscription_id) references public.subscriptions (tenant_id, id) on delete restrict on update no action;
alter table public.subscription_payment_proofs drop constraint subscription_payment_proofs_uploaded_by_fkey, add constraint subscription_payment_proofs_uploaded_by_fkey foreign key (tenant_id, uploaded_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.suppliers drop constraint suppliers_archived_by_fkey, add constraint suppliers_archived_by_fkey foreign key (tenant_id, archived_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.suppliers drop constraint suppliers_internal_branch_id_fkey, add constraint suppliers_internal_branch_id_fkey foreign key (tenant_id, internal_branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.suppliers drop constraint suppliers_internal_department_id_fkey, add constraint suppliers_internal_department_id_fkey foreign key (tenant_id, internal_department_id) references public.departments (tenant_id, id) on delete restrict on update no action;
alter table public.tasks drop constraint tasks_archived_by_fkey, add constraint tasks_archived_by_fkey foreign key (tenant_id, archived_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.tasks drop constraint tasks_created_by_fkey, add constraint tasks_created_by_fkey foreign key (tenant_id, created_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.tasks drop constraint tasks_owner_branch_id_fkey, add constraint tasks_owner_branch_id_fkey foreign key (tenant_id, owner_branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.tasks drop constraint tasks_owner_department_id_fkey, add constraint tasks_owner_department_id_fkey foreign key (tenant_id, owner_department_id) references public.departments (tenant_id, id) on delete restrict on update no action;
alter table public.tasks drop constraint tasks_owner_user_id_fkey, add constraint tasks_owner_user_id_fkey foreign key (tenant_id, owner_user_id) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.user_branch_assignments drop constraint user_branch_assignments_branch_id_fkey, add constraint user_branch_assignments_branch_id_fkey foreign key (tenant_id, branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.user_branch_assignments drop constraint user_branch_assignments_created_by_fkey, add constraint user_branch_assignments_created_by_fkey foreign key (tenant_id, created_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.user_branch_assignments drop constraint user_branch_assignments_department_id_fkey, add constraint user_branch_assignments_department_id_fkey foreign key (tenant_id, department_id) references public.departments (tenant_id, id) on delete restrict on update no action;
alter table public.user_branch_assignments drop constraint user_branch_assignments_user_id_fkey, add constraint user_branch_assignments_user_id_fkey foreign key (tenant_id, user_id) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.user_role_assignments drop constraint user_role_assignments_assigned_by_fkey, add constraint user_role_assignments_assigned_by_fkey foreign key (tenant_id, assigned_by) references public.users (tenant_id, id) on delete restrict on update no action;
alter table public.user_role_assignments drop constraint user_role_assignments_branch_id_fkey, add constraint user_role_assignments_branch_id_fkey foreign key (tenant_id, branch_id) references public.branches (tenant_id, id) on delete restrict on update no action;
alter table public.user_role_assignments drop constraint user_role_assignments_department_id_fkey, add constraint user_role_assignments_department_id_fkey foreign key (tenant_id, department_id) references public.departments (tenant_id, id) on delete restrict on update no action;
alter table public.user_role_assignments drop constraint user_role_assignments_user_id_fkey, add constraint user_role_assignments_user_id_fkey foreign key (tenant_id, user_id) references public.users (tenant_id, id) on delete restrict on update no action;

