-- MONEY-2 -- owner decision, ratified 2026-09-09. The three columns MONEY-1 gave only the NaN rule
-- do NOT share one sign rule, and this migration is the point at which that stops being an open
-- question and becomes enforced behaviour.
--
-- ================================================================================================
-- WHAT THE OWNER DECIDED, AND WHAT IS DELIBERATELY NOT DONE HERE
--
--   * `public.financial_accounts.opening_balance` -- SIGNED VALUES REMAIN VALID. A bank account
--     opening overdrawn is an ordinary banking fact, and a blanket non-negative rule here would
--     make an honest opening position unrecordable. **No constraint is added to that column by
--     this migration, and that omission is the decision rather than an oversight.** The NaN
--     defence (`financial_accounts_no_nan_check`, MONEY-1) is untouched and still applies.
--     A later reader completing the pattern by symmetry would be reversing a ratified decision.
--
--   * `public.quotations.total_amount`        -- never below zero.
--   * `public.quotation_items.total_amount`   -- never below zero.
--
--     A discount, correction or credit is represented explicitly, never by driving a whole
--     quotation or line total negative.
--
-- ================================================================================================
-- WHY A CHECK CONSTRAINT, AND WHY EXACTLY TWO OF THEM -- ONE ARITHMETIC AUTHORITY, PRESERVED
--
-- The totals were measured before anything was written, because "is this caller-authored, generated
-- or derived?" decides the enforcement layer:
--
--   * `quotation_items.total_amount` is CALLER-AUTHORED at the table door and GENERATED by the RPC:
--     `app.add_quotation_item` writes `p_quantity * p_unit_price`. Its siblings already carry
--     `quantity > 0` and `unit_price >= 0`, so the RPC's product is non-negative by construction --
--     but `authenticated` holds INSERT/UPDATE on the table, so PostgREST serves the column beside
--     the RPC and a direct write may set any number at all (BOOK-1's standing lesson: test both
--     doors).
--
--   * `quotations.total_amount` is DERIVED: the AFTER trigger `quotation_items_recompute_total`
--     (`app.recompute_quotation_total`) is the sole arithmetic authority, summing the line totals.
--     A direct `update public.quotations set total_amount = -500` sticks until the next item change
--     recomputes it, so the derived column has a writable door of its own.
--
-- THEREFORE: the invariant is enforced at the canonical source (the line) AND asserted on the
-- derived result (the header), and NO second calculator is introduced -- `recompute_quotation_total`
-- remains the only thing that computes a quotation total. The header constraint can only ever fire
-- on a hand-written value, because a sum of non-negative lines is non-negative; that is precisely
-- what makes it a backstop rather than a duplicate rule.
--
-- A CHECK is the right layer and a trigger is not: the rule is a statement about the new row alone
-- (PostgreSQL: a CHECK constraint may reference only the row being inserted or updated), it is
-- unconditional, and it therefore holds on EVERY reachable write path at once -- RPC, PostgREST
-- table door, the recompute trigger, and any future writer -- with no session, no permission and no
-- ordering assumption. Adding a trigger for a single-row numeric invariant that a constraint already
-- owns would be a second enforcement engine for one rule.
--
-- ZERO REMAINS LEGAL. `quotations.total_amount` and `quotation_items.total_amount` are both
-- NOT NULL DEFAULT 0, an empty draft quotation totals zero, and a zero-priced line is how a
-- complimentary service is already recorded (`app.add_quotation_item` accepts `p_unit_price = 0`
-- explicitly). `>= 0`, never `> 0`.
--
-- NaN: `x >= 0` is FALSE for NaN, so these constraints happen to reject it too -- but MONEY-1's
-- `*_no_nan_check` constraints are NOT removed. Two independent guards, neither relying on the
-- other, and the NaN constraint carries the error message that names the real problem.
--
-- EXISTING ROWS: `not valid` is NOT used. Both environments hold zero business rows, so the
-- constraints are added validated and the whole table is proven at migration time rather than
-- trusted.

alter table public.quotation_items
    add constraint quotation_items_total_amount_nonneg_check
    check (total_amount >= 0);

alter table public.quotations
    add constraint quotations_total_amount_nonneg_check
    check (total_amount >= 0);

comment on constraint quotation_items_total_amount_nonneg_check on public.quotation_items is
    'MONEY-2 (owner decision 2026-09-09): a quotation line total is never below zero. Enforced at the canonical source -- app.recompute_quotation_total sums these values, so a non-negative line total is what makes the derived header total non-negative. A discount or credit is represented explicitly, not by a negative line.';

comment on constraint quotations_total_amount_nonneg_check on public.quotations is
    'MONEY-2 (owner decision 2026-09-09): a quotation total is never below zero. This column is DERIVED by app.recompute_quotation_total from the line totals, so this constraint is the backstop on the table door PostgREST serves beside the RPC -- it cannot fire on a computed value, only on a hand-written one. No second calculator was introduced.';

-- ================================================================================================
-- THE SECOND CALCULATOR, FOUND BY THE TEST THAT ASSERTED THERE WAS ONLY ONE
--
-- MONEY-2's owner decision says "preserve ONE arithmetic authority". Asserting that as a test
-- (112, assertion 14) discovered that ORVION had TWO: `app.recompute_quotation_total` -- the AFTER
-- trigger installed by QUO-1 -- and a hand-written `update public.quotations set total_amount =
-- (select sum(...))` still standing at the end of `app.add_quotation_item`, which predates the
-- trigger and was never removed when QUO-1 made the trigger the authority.
--
-- It was harmless only by coincidence: the trigger fires on the INSERT, so by the time the RPC's own
-- statement ran it was recomputing a value the trigger had already written from the same source. But
-- it is a genuine duplicate authority -- the exact thing the owner decision forbids -- and the day
-- the two expressions diverge the winner would be decided by statement order rather than by design.
--
-- REMOVED, not left in place: the RPC now inserts the line and lets the trigger own the total, so
-- the sum expression exists exactly once in the system. Every other line of the function is
-- unchanged, and 73_quotation_total_derivation_test.sql (which proves header == lines on the RPC
-- path, and mutation-tests the trigger) is what holds this correct.
create or replace function app.add_quotation_item(
    p_quotation_id uuid,
    p_service_type_code text,
    p_unit_price numeric,
    p_quantity numeric default 1,
    p_description text default null
)
returns uuid
language plpgsql
set search_path = ''
as $fn$
declare
    v_tenant uuid := app.current_tenant_id();
    v_q record;
    v_item uuid;
begin
    if v_tenant is null then
        raise exception 'no active tenant for caller';
    end if;
    perform app.authorize('CREATE_QUOTATION');

    select * into v_q from public.quotations
    where id = p_quotation_id and tenant_id = v_tenant
    for update;
    if not found then
        raise exception 'quotation is not in your tenant';
    end if;
    if v_q.quotation_status_code <> 'draft' then
        raise exception 'items can only be added to a draft quotation (status: %)', v_q.quotation_status_code;
    end if;
    if not exists (
        select 1 from public.catalog_values
        where catalog_type_code = 'service_type' and code = p_service_type_code
    ) then
        raise exception 'unknown service_type_code: %', p_service_type_code;
    end if;
    if p_unit_price < 0 or p_quantity <= 0 then
        raise exception 'unit_price must be >= 0 and quantity > 0';
    end if;

    insert into public.quotation_items (
        tenant_id, quotation_id, service_type_code, description,
        quantity, unit_price, total_amount, currency_code
    ) values (
        v_tenant, p_quotation_id, p_service_type_code, p_description,
        p_quantity, p_unit_price, p_quantity * p_unit_price, v_q.currency_code
    )
    returning id into v_item;

    -- MONEY-2: the header total is NOT recomputed here. `quotation_items_recompute_total` has
    -- already done it from the same source, and one arithmetic authority is the decision.

    return v_item;
end;
$fn$;

comment on function app.add_quotation_item(uuid, text, numeric, numeric, text) is
    'MONEY-2 (2026-09-09): the trailing recompute of quotations.total_amount was removed. QUO-1 made app.recompute_quotation_total the sole authority for that value and this function had kept a second, identical sum expression -- harmless only because the trigger runs first. The line total it writes is quantity * unit_price, and both operands already carry their own constraints, so the value it inserts can never be negative.';

comment on column public.financial_accounts.opening_balance is
    'Signed. A negative opening balance is a valid record of an account that opens overdrawn -- MONEY-2 (owner decision 2026-09-09) explicitly REFUSED a non-negative rule here, unlike quotations.total_amount and quotation_items.total_amount which received one in the same decision. Only the MONEY-1 NaN defence applies. Do not add a non-negative constraint by symmetry with the quotation columns.';
